spring.datasource.url=jdbc:mysql://switchback.proxy.rlwy.net:34633/railway?allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=cAHawRQCxuGfQGQcvvpBJPLWEIIEyIP
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=${PORT:6497}
upload.path=uploads/

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=INFO
